### PR TITLE
Update Workflows to Version 0.16.1

### PR DESCRIPTION
**Pull request by Bisaloo**
:robot: This is an automated build

Update Workflows from sandpaper version 0.12.4 -> 0.16.1

- Auto-generated by [create-pull-request][1] on 2023-12-19T00:32+00:00

[1]: https://github.com/carpentries/create-pull-request/tree/main

### CODE REVIEW

**Comment by avallecam** [comment]
Hi Hugo, thank you for looking up on this. 

I'll ask questions here and then proceed to approve the merging in the other repos:
- These are automated builds, as I read in the PR comment. How do you run it?
- In the following iterations, how should we run these updates?

Reference documentation: https://carpentries.github.io/sandpaper/articles/automated-pull-requests.html#setting-up-a-pull-request-bot

**Comment by Bisaloo** [comment]
They will run automatically [each week](https://github.com/epiverse-trace/research-compendium/blob/da9f187c404c639733abc0d44927fdd01a841842/.github/workflows/update-workflows.yaml#L14-L16) or [each month](https://github.com/epiverse-trace/research-compendium/blob/da9f187c404c639733abc0d44927fdd01a841842/.github/workflows/update-cache.yaml#L21-L35) depending on the workflow.

I've exceptionally triggered them manually via https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow.

**Comment by avallecam** [comment]
> They will run automatically [each week](https://github.com/epiverse-trace/research-compendium/blob/da9f187c404c639733abc0d44927fdd01a841842/.github/workflows/update-workflows.yaml#L14-L16) or [each month](https://github.com/epiverse-trace/research-compendium/blob/da9f187c404c639733abc0d44927fdd01a841842/.github/workflows/update-cache.yaml#L21-L35) depending on the workflow.
> 
> I've exceptionally triggered them manually via https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow.

Nice to see where the workflow is configured.

As far as I've been following the [workflow actions](https://github.com/epiverse-trace/research-compendium/actions), they have been running automatically since the start of the repository with that frequency. examples for [package cache](https://github.com/epiverse-trace/research-compendium/actions/runs/7175571476) and [workflow](https://github.com/epiverse-trace/research-compendium/actions/runs/7175196945) updates

But this manual trigger was exceptional. This created a PR. 

- Should we now expect to receive these automated PRs?
- Should we do this manual triggering with a certain frequency away from the monthly and weekly frequency?

**Comment by Bisaloo** [comment]
> Should we now expect to receive these automated PRs?

Yes, because I have created the missing token and added it as a secret to the relevant repositories.

> Should we do this manual triggering with a certain frequency away from the monthly and weekly frequency?

No, it's probably not necessary. I've done it this time to test that the token was working correctly and to ensure potential issues are fixed ASAP since we went a long time without updating the infrastructure.

**Review by avallecam — APPROVED** [review]

**Comment by avallecam** [comment]
ready to merge 🚀

**Pull request merged**
